### ISSUE TITLE
[Feature request] Implementation as an operarion mode and other improvements

### ISSUE THREAD

**Issue by PladsElsker** [Scholar01/sd-webui-bg-mask#2]
Hello, first I want to say thank you for making this extension! I love the idea. 

I wanted to suggest a few changes to improve the user experience: 
- In its current state, the extension is implemented as an accordion script, but it would make way more sense to implement it as an img2img operation mode. This implies hijacking your way through gradio to add a new tab right next to the "Inpaint upload" and "Batch" tabs. The parameters for the alpha matting would go right under the tab, next to the mask blur. Like this, the user could have instant feedback on how the mask looks like. 
- I think it would make sense to add an accordion in the txt2img tab to generate an image with a mask. 
- I tried to invert the mask in inpaint operation mode, but it doesn't seem to work. It doesn't seem to fit into the other existing ui options super well. Again I think this could be improved if it was implemented as an operation mode. 

Do you accept PRs? I can try my hand at it if you want, I had to add my own operation mode in the last extension I made.

**Comment by PladsElsker** [comment]
Nevermind, I'll create my own repo I think. 
I might reference this repo in the readme because I'll use it as a reference for some things.

**Comment by Scholar01** [comment]
Sorry, just saw your message, I'll gladly take pr!

**Comment by PladsElsker** [comment]
Thank you for reaching back. 
I've looked at it a bit more, and I'm not sure making a PR would be the best approach. 

Basically, I have to re-write the whole pipeline of the extension to make it fit into an img2img tab, so it's almost the same thing as starting from scratch. 

I already wrote the code to hijack the tab in an extensible way in another extension I made. The problem now is that implementing this over and over again will create tons of duplicated code, and will most certainly lead to extension incompatibilities over time. This is because the way to "hijack a new img2img tab" is super hacky and unstable if everyone does it "their way". 
Furthermore, it will most likely break for the upcomming versions of the webui. 

The best way to fix this would be to make a PR into A1111, but there's so much that needs to change. I don't think such a PR would be easily accepted by them. 

To address this, I would like to try to make a pip package to cleanly hijack the img2img tabs (img2img operation modes). 
Extensions would then import the tab hijacking mechanism through the pip package. 
If there's breaking changes, only the pip package would need to be updated. 

Anyways, I don't plan on making a PR in this repo for now. 
If I do successfully implement the pip package, I'll come back to this and probably make a PR. 
Otherwise, I might just implement it without the pip package in a new repo of my own.

**Comment by Scholar01** [comment]
Looking forward to your work! 😀

**Comment by PladsElsker** [comment]
Hello, I wanted to let you know the pip package is done! 🎉
https://pypi.org/project/sdwi2iextender/

As of now, I have 3 extensions that use it, it seems relatively stable (for now). 
You can have a look if you're interested:
- https://github.com/John-WL/sd-webui-inpaint-difference
- https://github.com/John-WL/sd-webui-inpaint-background
- https://github.com/John-WL/sd-webui-mask-fractioner
